name: Build KernelSU
permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      model:
        required: true
        type: string
        default: samsung24u
      soc:
        required: true
        type: string
        default: pineapple
      branch:
        required: true
        type: string
        default: main
      android_version:
        required: true
        type: string
        default: android14
      kernel_version:
        required: true
        type: string
        default: 6.1
      lto:
        required: false
        type: string
        default: thin

jobs:
  build-kernel-samsung-kernelsuNext-susfs:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y clang llvm lld git zip build-essential xz-utils bison flex libz-dev libssl-dev libelf-dev bc cpio python3 pahole lz4

      - name: Install Repo and Python
        run: |
          sudo apt update
          sudo apt install repo python3 python-is-python3

      - name: Set CONFIG Environment Variable
        run: |
          CONFIG="${{ inputs.model }}"
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
          echo "CONFIG set to: $CONFIG"

      - name: Clone AnyKernel3 and Other Dependencies
        run: |
          echo "Cloning AnyKernel3 and other dependencies..."
          ANYKERNEL_BRANCH="main"
          SUSFS_BRANCH="gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}"
          echo "Using branch for AnyKernel3: $ANYKERNEL_BRANCH"
          echo "Using branch for SUSFS: $SUSFS_BRANCH"
          git clone https://github.com/Felixardian/AnyKernel3.git

      - name: Initialize and Sync Kernel Source
        run: |
          echo "Creating folder for configuration: $CONFIG..."
          mkdir -p "$CONFIG"
          cd "$CONFIG"
          echo "Cloning kernel source..."
          git clone --branch ${{ inputs.branch }} --single-branch https://github.com/Felixardian/Samsung24U_sm8650_kernel.git .
          git --version
          git status

      - name: Add KernelSU
        run: |
          cd "$CONFIG"
          echo "Adding KernelSU..."
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          
      - name: Add SUSFS Configuration Settings
        run: |
          cd "$CONFIG"
          echo "Adding configuration settings to pineapple_gki_defconfig..."
          echo "CONFIG_KSU=y" >> ./arch/arm64/configs/pineapple_gki_defconfig

      - name: Set Environment Variables
        run: |
          TARGET_DEFCONFIG="${{ inputs.soc }}_gki_defconfig"
          LOCALVERSION="-${{ inputs.android_version }}-Felixardian"
          if [[ "${{ inputs.lto }}" == "thin" ]]; then
            LOCALVERSION+="-thin"
          fi
          echo "TARGET_DEFCONFIG=$TARGET_DEFCONFIG" >> $GITHUB_ENV
          echo "LOCALVERSION=$LOCALVERSION" >> $GITHUB_ENV
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "LLVM=1" >> $GITHUB_ENV
          echo "LLVM_IAS=1" >> $GITHUB_ENV

      - name: Configure Kernel
        run: |
          cd "$CONFIG"
          echo "Configuring kernel..."
          make -j$(nproc) O=$(pwd)/out ARCH=$ARCH $TARGET_DEFCONFIG
          ./scripts/config --file out/.config \
            -d UH \
            -d RKP \
            -d KDP \
            -d SECURITY_DEFEX \
            -d INTEGRITY \
            -d FIVE \
            -d TRIM_UNUSED_KSYMS
          if [[ "${{ inputs.lto }}" == "thin" ]]; then
            ./scripts/config --file out/.config -e LTO_CLANG_THIN -d LTO_CLANG_FULL
          fi

      - name: Build Kernel
        run: |
          cd "$CONFIG"
          echo "Building kernel..."
          make -j$(nproc) O=$(pwd)/out ARCH=$ARCH LOCALVERSION=$LOCALVERSION CC=$CC LLVM=$LLVM LLVM_IAS=$LLVM_IAS
      - name: Prepare AnyKernel3 Folder
        run: |
          mkdir -p AnyKernel3
          cp "$CONFIG/out/arch/arm64/boot/Image" AnyKernel3/zImage

      - name: Create ZIP Files for Different Formats
        run: |
          cd AnyKernel3
          ZIP_NAME="${{ inputs.model }}_${{ inputs.android_version }}_${{ inputs.kernel_version }}_LKM.zip"
          zip -r "../$ZIP_NAME" .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ env.CONFIG }}
          path: |
            *.zip      
